#############################
# eZProtector by Dvargas135 #
#############################
#
# Plugin prefix for warns/notifies
prefix: '&3[&beZProtector&3] &b'
##
# Console update notifier
updater: true
##
# If you have all the mods enabled, your console will be spammed by logging all the mods.
log-blocked-mods: false
##
# The default notify message, will only be used for the commands
# /plugins, /pl, /a, /about, /?, /ver, /version, /help, /icanhasbukkit,
# and the ones specified in block-commands
default-notify-message: '&e%player% tried to do the command %command%'
##
# Error message displayed to the players without any access of the plugin.
error-message: '&cNo permission.'
#
# Customised plugin list, commas are imperative.
# Showed if the 'custom-plugins' option is set to true.
custom-plugins:
  enabled: true
  plugins: Fully, Custom, Plugins
  # This message will only show if the above option is set to false.
  message: '&4Your abuse has been sent to the admins.'
  # Notify to all the players with the permission ezprotector.notify.command.plugins
  notify: true
##
# Block the tab completion or not. (permission ezprotector.bypass.tab-completion)
tab-completion:
  # disabled = blocked; if it's true, the tab completion will be blocked. (dumb explanation)
  disable: true
  warn:
    enabled: false
    # If players spam the tab key they'll also get spammed with the below message. ONLY if warn is set to true.
    message: '&cYou don''t have permission to do this.'
##
# Message showed for every command including ':' in it. 
# An example could be "/bukkit:help", "/essentials:warp", etc.
# This will only work if the option "block-hidden-syntaxes" is set to true.
block-hidden-syntaxes:
  enabled: true
  message: '&cThat syntax is forbidden.'
  # Notify to all the players with the permission ezprotector.notify.hiddensyntaxes
  notify: true
  # For YAML, if you want to add a message with an apostrophe such as "don't",
  # you have to type double apostrophe: don''t.
  notify-message: '&e%player% tried to do a command with bukkit''s hidden syntax. (%command%)'
##
# Will deny the listed commands showing the message set in 'error-message'.
block-commands:
  enabled: true
  message: '&cYou don''t have permission.'
  # Notify to all the players with the permission ezprotector.notify.blockedcommands
  notify: true
  # Command list for regular players.
  commands:
  - a
  - about
# - help
  - icanhasbukkit
##- pl      # These two commands are handled by the customized plugins section.
##- plugins # They don't need to be added here. (/plugins and /pl).
  - ver
  - version
  - '?'
  - op
  - plugman list
##
# Blockage of commands for opped players
block-op-commands:
  enabled: true
  # Error message for opped players that are not in the bypassed-players list
  message: '&cThis command can only be executed from console.'
  # Notify ONLY to the bypassed players (see below).
  notify: true
  notify-message: '&eOpped player %player% tried to do %command%'
  # Command list (Only blocks for opped players)
  commands:
  - ezp
  - reload
  - featherboard resetconfig
  - command_without_slash
  # Who can bypass this option?
  # This only applies to the op commands section and to opped players.
  bypassed-players:
  - Notch
##
# Sign exploit blockage
block-anti-sign-hack:
  enabled: true
  # If a player tries to abuse the sign exploit, a broadcasted message
  # will be sent to all the players with the permission ezprotector.notify.signhack
  warning-message: '&4WARN &c- &f%player% attempted to do the sign exploit, but failed.'
  # The command that will be executed if someone attempts to do the sign exploit.
  punish-command: kick %player% &4This exploit is forbidden!
##
# Mod blocker
mods:
  wdl:
    block: false
    warning-message: '&4WARN &c- &f%player% tried to join with the world downloader mod, but failed.'
    punish-command: kick %player% &4The World Downloader Mod is not allowed.
  schematica:
    block: false
  voxelmap:
    block: false
  damageindicators:
    block: false
  reiminimap:
    block: false
  forge:
    block: false
    warning-message: '&4WARN &c- &f%player% tried to join with the Forge mod, but failed.'
    punish-command: kick %player% &4The Forge mod is not allowed.
  5zig:
    block: false
  betterpvp:
    block: false
  liteloader:
    block: false
    warning-message: '&4WARN &c- &f%player% tried to join with the LiteLoader mod, but failed.'
    punish-command: kick %player% &4The LiteLoader mod is not allowed.
  bettersprinting:
    block: false
  labymod:
    block: false
  smartmoving:
    block: false
##
# Thanks for using eZProtector, don't forget to leave a review! :)
