# eZProtector | Version ${project.version}
# To see what are the placeholders available to you, read the information page here: https://git.io/vpDio

[tab-completion]
    blocked = true
    whitelist = false

    commands = [
        "about",
        "help",
        "velocity",
        "?",
    ]

[hidden-syntaxes]
    blocked = true
    error-message = "&7[&aeZProtector&7]&f &4That command syntax is forbidden!"
    whitelisted = [
        "whitelisted:commands",
        "with:hidden",
        "syntaxes:here"
    ]

    [hidden-syntaxes.notify-admins]
        enabled = true
        message = "&7[&aeZProtector&7]&f &e%player% &ftried to use a command with a hidden syntax &4(/%command%)"

    [hidden-syntaxes.punish-player]
        enabled = false
        command = "kick %player% %errormessage%"

[custom-commands]
    blocked = true
    error-message = "&7[&aeZProtector&7]&f You don''t have the permission to use this command! &4(/%command%)"
    commands = [
        "a",
        "about",
        "icanhasbukkit",
        "?",
        "plugman list",
        "command_without_slash"
    ]

    [custom-commands.notify-admins]
        enabled = true
        message = "&7[&aeZProtector&7]&f &e%player% &ftried to use a blocked command &4(/%command%)"

    [custom-commands.punish-player]
        enabled = false
        command = "kick %player% %errormessage%"

[mods]
  5zig = false
  betterpvp = false
  bettersprinting = false
  schematica = false
  voxelmap = false
  wdl = false

  [mods.fabric]
      block = false
      warning-message = "&7[&aeZProtector&7]&f &e%player% &ftried to join while having Forge installed"
      punish-command = "kick %player% &4The Forge mod is not allowed."

  [mods.forge]
    block = false
    warning-message = "&7[&aeZProtector&7]&f &e%player% &ftried to join while having Forge installed"
    punish-command = "kick %player% &4The Forge mod is not allowed."

  [mods.liteloader]
    block = false
    warning-message = "&7[&aeZProtector&7]&f &e%player% &ftried to join while having LiteLoader installed"
    punish-command = "kick %player% &4The LiteLoader mod is not allowed."

  [mods.rift]
    block = false
    warning-message = "&7[&aeZProtector&7]&f &e%player% &ftried to join while having LiteLoader installed"
    punish-command = "kick %player% &4The LiteLoader mod is not allowed."
