# eZProtector | Version ${project.version}
# To see what are the placeholders available to you, read the information page here: https://git.io/vpDio

# Here you can modify the prefix of the plugin.
prefix: '&7[&aeZProtector&7]&f'

# This module blocks tab completion for certain commands.
tab-completion:
  blocked: true
  # If this is set to true, the commands in the list will be THE ONLY ones to be tab completed
  whitelist: false
  commands:
  - '?'
  - about
  - bukkit:?
  - bukkit:about
  - bukkit:help
  - bukkit:pl
  - bukkit:plugins
  - bukkit:ver
  - bukkit:version
  - help
  - icanhasbukkit
  - pl
  - plugins
  - ver
  - version

# This blocks players from using commands such as /bukkit:help or /essentials:warp, since they can use that to bypass various protections.
hidden-syntaxes:
  blocked: true
  error-message: '%prefix% That command syntax is forbidden!'
  # If you add a command to this list, it will not be blocked.
  whitelisted:
  - whitelisted:commands
  - with:hidden
  - syntaxes:here
  notify-admins:
    enabled: true
    message: '%prefix% &e%player% &ftried to use a command with a hidden syntax &4(%command%)'
  punish-player:
    enabled: false
    command: 'kick %player% %errormessage%'

# This option allows you to set a custom list of plugins that will be shown if players do /plugins
custom-plugins:
  enabled: true
  plugins: Fully, Custom, Plugins
  # The player will not see an error message, but admins can still be notified
  notify-admins:
    enabled: true
    message: '%prefix% &e%player% &ftried to see the server plugins'

# Same deal as with the custom plugins above, but for the version command!
custom-version:
  enabled: true
  # It shows up as "This server is running server version Custom Version"
  version: "Custom Version"
  # The player will not see an error message, but admins can still be notified
  notify-admins:
    enabled: true
    message: '%prefix% &e%player% &ftried to see the server version'

# This option allows you to block any command you wish by adding it to the list!
custom-commands:
  blocked: true
  error-message: '%prefix% You don''t have the permission to use this command! &4(%command%)'
  commands:
  - a
  - about
  - icanhasbukkit
  #- pl
  #- plugins
  #- ver
  #- version
  - '?'
  - plugman list
  - command_without_slash
  notify-admins:
    enabled: true
    message: '%prefix% &e%player% &ftried to use a blocked command &4(%command%)'
  punish-player:
    enabled: false
    command: 'kick %player% %errormessage%'

# This section allows you to block various mods (and even punish players for some of them!)
mods:
  5zig:
    block: false
  # This option also blocks Xaero's Minimap!
  betterpvp:
    block: false
  bettersprinting:
    block: false
  fabric:
    block: false
    warning-message: '%prefix% &e%player% &ftried to join while having Fabric installed'
    punish-command: kick %player% &4Fabric usage is not allowed.
  forge:
    block: false
    warning-message: '%prefix% &e%player% &ftried to join while having Forge installed'
    punish-command: kick %player% &4Forge usage is not allowed.
  liteloader:
    block: false
    warning-message: '%prefix% &e%player% &ftried to join while having LiteLoader installed'
    punish-command: kick %player% &4LiteLoader usage is not allowed.
  rift:
    block: false
    warning-message: '%prefix% &e%player% &ftried to join while having Rift installed'
    punish-command: kick %player% &4Rift usage is not allowed.
  schematica:
    block: false
  voxelmap:
    block: false
  wdl:
    block: false

# This is the end of the config! Yay!
